import type { Metadata } from "next";
import { coreInfo } from "@/components/data/core";

import { Suspense } from "react";
import ProfileHeader from "./_components/navButtons";

export const metadata: Metadata = {
  title: `Profile | ${coreInfo.name}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Suspense>
        <div className="mx-auto flex max-w-384 flex-col items-start justify-start gap-2 md:flex-row">
          <ProfileHeader />
          <div className="bg-background w-full flex-1 rounded-md border">
            {children}
          </div>
        </div>
      </Suspense>
    </>
  );
}
