import type { Metadata } from "next";
import { coreInfo } from "@/components/data/core";
import ProfileHeader from "@/components/layout/ProfileHeader";

export const metadata: Metadata = {
  title: `Profile | ${coreInfo.name}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
