import type { Metadata } from "next";
import { coreInfo } from "@/components/data/core";

import { Suspense } from "react";
import ProfileHeader from "./_components/navButtons";

export const metadata: Metadata = {
  title: `Profile | ${coreInfo.name}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Suspense>
        <div className="flex flex-col gap-2 md:flex-row items-start justify-start max-w-384 mx-auto">
          <ProfileHeader />
          <div className="flex-1 bg-background rounded-md border w-full">

          {children}
          </div>
        </div>
      </Suspense>
    </>
  );
}
