import type { Metadata } from "next";
import HeadNavCombo from "./_dash_components/layout/headNavCombo";

export const metadata: Metadata = {
  title: "Dashboard | RUAIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <HeadNavCombo>{children}</HeadNavCombo>;
}
