import type { Metadata } from "next";
import HomeNav from "@/components/layout/homeNav";
import Footer from "@/components/layout/Footer";
import PathOptions from "@/components/layout/PathOptions";
import { coreInfo } from "@/components/data/core";

export const metadata: Metadata = {
  title: `Home | ${coreInfo.name}`,
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HomeNav />
      <PathOptions />
      <main className="flex-1 pb-12">{children}</main>
      <Footer />
    </>
  );
}
